### ISSUE TITLE
Zemljevidi in poročilo

### ISSUE THREAD

**Issue by jaanos** [BlazOrsos/APPR-2014-15#3]
Tvoja zemljevida sta povsem nečitljiva - imena držav se prekrivajo in marsikje popolnoma prekrijejo barvo, ki jo želiš pokazati. Namesto, da izpisuješ vsa imena, naredi selekcijo - prikaži npr. samo imena največjih držav, pa morda lahko ob tem izpostaviš največje onesnaževalce. Seveda naj ostane zemljevid ob tem čitljiv - po potrebi lahko imenom spreminjaš velikost, jih premakneš, ali pa skrajšaš.

Še vedno nimaš poročila v LaTeXu. Tja seveda vključi tudi svoje grafe, saj boš to pokazal zadnji teden na predstavitvi.

**Comment by BlazOrsos** [comment]
Spoštovani,

zavedam se mojega problema a ga nažalost ne znam popravit, poskusil sem že
vse možno, a mi vedno javi napako "Error using packet 1, loc should be
numeric". Enostavno nevem kako naj naredim to selekcijo, prosil bi vas, da
mi malo pomagate. Prav tako, neven ali naj vključim v poročilo vseh 230
grafov ali lahko na kakšen način naredim selekcijo?

Najlepša hvala.

Lep pozdrav,
Blaž

Dne 13. januar 2015 01.55 je Janoš Vidali <notifications@github.com>
napisal/-a:

**Comment by jaanos** [comment]
Izbor držav lahko narediš na roko, ali pa po kakšnem drugem kriteriju. Tako lahko npr. vzameš 10 največjih držav na svetu in jih potem vzameš kot indekse razpredelnici `koordinate` in vektorju `imena`:
```R
izbor <- c("Russian Federation", "Canada", "China", "United States", "Brazil",
           "Australia", "India", "Argentina", "Kazakhstan", "Algeria")
```
Da bo zemljevid čitljiv, si lahko nekoliko prirediš koordinate, kjer bodo izrisana imena. Po potrebi lahko imena tudi zarotiraš (npr. za Argentino) - kot rotacije podaš s parametrom `srt` pri izpisovanju imen. Tako lahko narediš npr.
```R
koordinate["Algeria",1] <- koordinate["Algeria",1] - 1
koordinate["Argentina",1] <- koordinate["Argentina",1] - 2
koordinate["Canada",1] <- koordinate["Canada",1] - 1

rot <- ifelse(izbor == "Argentina", 90, 0)
```
Sedaj lahko narišeš zemljevid z izbranimi imeni:
```R
print(spplot(svet, "izpusti",
             sp.layout = list("sp.text", koordinate[izbor,], imena[izbor],
                              cex = 0.4, col="black", srt = rot),
             col.regions = heat.colors(100)))
```
Prej si imel tukaj neobstoječi spremenljivki `koordinate2` in `imena2`, zaradi česar ti program ni deloval. Naj opozorim še, da je `col.regions` parameter ukaza `spplot` in naj bo torej izven seznama pri `sp.layout`. Podobno seveda lahko narediš še pri drugem grafu (lahko uporabiš že pripravljene spremenljivke).

Pri zemljevidu populacije deli podatke z npr. `1000000`, da se izogneš eksponentni notaciji na lestvici. Zemljevidoma dodaj tudi naslov (parameter `main` pri ukazu `spplot`.

Ni smiselno, da v poročilo vključuješ vse grafe. Pri vključevanju posameznih grafov si pomagaj z ukazom `\includepdf` iz paketa `pdfpages`, ki ga imaš že vključenega. Če želiš npr. vključiti strani 1, od 3 do 6, in 100, lahko tako narediš:
```LaTeX
\includepdf[pages={1,3-6,100}]{../slike/Grafi_rasti_populacije.pdf}
```
Seveda izberi le nekaj najbolj zanimivih grafov. Vsak graf bo tako na svoji strani. Enako lahko narediš tudi za zemljevide (tam imaš seveda samo eno stran v dokumentih PDF), lahko pa jih vstaviš med besedilo. Da ne bodo premajhni, si pomagaj z ukazom `\makebox`, ki ti ustrezno poravna sliko, če je širša od besedila:
```LaTeX
\makebox[\textwidth][c]{
\includegraphics[width=1.2\textwidth]{../slike/Graf_Populacija_2010.pdf}
}
```

**Comment by BlazOrsos** [comment]
Spoštovani,

popravil sem zemljevide in uredil poročilo, načeloma naj bi bilo zdaj vse
vredu. Iskreno se vam zahvaljujem za pomoč.

Lep pozdrav,
Blaž

Dne 13. januar 2015 18.49 je Janoš Vidali <notifications@github.com>
napisal/-a:

**Comment by jaanos** [comment]
Je urejeno, tako da zapiram.
